apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: node-container
        image: edraithenni/goofy-app:f23751d0a98389cb65f6fb275946d381bcca52ce
        ports:
        - containerPort: 3000
