apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: node-container
        image: edraithenni/goofy-app:7fdf9468a2cdf2ae15c91a43fa459e22ab8da947
        ports:
        - containerPort: 3000
