apiVersion: apps/v1
kind: Deployment
metadata:
  name: goofy-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: node-container
        image: edraithenni/goofy-app:30e5c4f98084bad2d55dca13a85fdddbfee625b6
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: images-storage
          mountPath: /app/public/images 
      volumes:
      - name: images-storage
        persistentVolumeClaim:
          claimName: goofy-app-images-pvc
